CREATE TABLE movie_suggester_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT,
    last_name TEXT,
    username text not null unique,
    password text not null,
    bio text,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

ALTER SEQUENCE movie_suggester_users_id_seq RESTART with 100;