CREATE TABLE movie_suggester_follows (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    follower_id INTEGER REFERENCES movie_suggester_users(id) not null,
    friend_id INTEGER REFERENCES movie_suggester_users(id) not null,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);