CREATE TABLE movie_suggester_movie_ratings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES movie_suggester_users(id) not null,
    movie_id INTEGER REFERENCES movie_suggester_movies(id) not null,
    star_rating INTEGER not null,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);