CREATE TYPE reason_to_ignore AS ENUM ('watched_it', 'not_intrested');

CREATE TABLE movie_suggester_movies_to_ignore (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES movie_suggester_users(id) not null,
    movie_id INTEGER REFERENCES movie_suggester_movies(id) not null,
    ignore reason_to_ignore not null,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);